= Submission API Documentation
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

== Overview

This describes the resources that make up the EMBL-EBI submissions API.
If you have any queries or requests, please contact mailto:subs-help@ebi.ac.uk[support].

All API access is over HTTP, and accessed from `http://www.ebi.ac.uk/submissions/api`.
All data is sent and received as JSON. Blank fields are included as `null` instead of being omitted.

=== HTTP Verbs

This API aims to use appropriate HTTP verbs for each action


[cols=2*,options="header"]
|===
|Verb
|Description


|`GET`|Used for retrieving resources
|`POST`|Used for creating resources
|`PATCH`|Used to modify a resource
|`PUT`|Used for replacing resources
|`DELETE`|Used for deleting resources
|`OPTIONS`|Can be used to determine which verbs can be used for a resource
|`HEAD`|Returns whether a resource is available
|===

=== HTTP status codes

[cols=2*,options="header"]
|===
|Status code
|Description


|`200 OK`|The request completed successfully
|`201 Created`|Returned after successfully creating a new resource with a `POST` request
|`204 No Content`|Returned after a request successfully deleted a resource.
|`304 Not Modified`|Returned in response to a conditional `GET` request, when the resource has not been modified
|`400 Bad Request`|The request was malformed. The response body will include an error providing further information
|`405 Method Not Allowed`|The request used a method that is not permitted
|`412 Precondition Failed`|Returned in response to a conditional `PATCH`, `PUT` or `DELETE`, when the condition did not match the resource state
|===

=== Authentication

TODO, pending implementation details from AAP. Get a https://jwt.io/[JWT] token from AAP. Include it as the Authorization header in
requests to the submissions API.

[source,bash]
----
$ curl 'http://www.ebi.ac.uk/submissions/api' -i -H 'Accept: application/hal+json' -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ'
----


=== Errors

There are several types of client errors on API calls that receive request bodies.

* Sending invalid JSON will result in a `400 Bad Request` response
include::{snippets}/invalid-json/curl-request.adoc[]
include::{snippets}/invalid-json/http-response.adoc[]
* Sending the wrong type of JSON values will result in a `400 Bad Request` response.
include::{snippets}/json-array-instead-of-object/curl-request.adoc[]
include::{snippets}/json-array-instead-of-object/http-response.adoc[]
* Sending invalid fields will result in a `400 Bad Request` response.
include::{snippets}/invalid-submission/curl-request.adoc[]
include::{snippets}/invalid-submission/http-response.adoc[]

All error objects have properties so that your client can tell what the problem is. There's also an error code
so that you know what is wrong with the field.

[cols=2*,options="header"]
|===
|Error name
|Description

|missing_field |This means a required field has not been set
|invalid |This means the contens of this field are invalid
|resource_locked |The resource cannot be changed
|already_exists |Another resource with the same value already exists

|===

=== Hypermedia

This API uses hypermedia, and resources include links to other resources in their responses. Responses are in
http://stateless.co/hal_specification.html[HAL] format. Links can be found beneath the `_links` key. API users should
not build links themselves, but should use these links to navigate between resources. Clients should discover resources
and available actions by consuming the `_links`.

Links may be returned in templated form, requiring expansion prior to use. This is primarily true for search resources.
Templated links follow https://tools.ietf.org/html/rfc6570[RFC6570].

=== Collection resources

Collection resources represent a set of individual resources, often presented as summary representations. Each element
will have its own `_links` element. Following the `self` link from one of these elements will bring you to the
detailed representation.

==== Summary representations

When fetching a list of resources, the response includes a subset of the attributes for that resource.
For performance reasons some attributes are excluded from the summary representation.
These are available from the detailed representation.

Example: When you get a list of samples, you get the summary representation of each sample.

include::{snippets}/samples/by-submission/curl-request.adoc[]
include::{snippets}/samples/by-submission/http-response.adoc[]

==== Paging

Requests that return multiple items will be paginated to 20 items by default. You can specify a specific pages with the
`?page` parameter. Page number is 1-based and in the absence of a `?page` parameter the first page is returned. You can also set a custom page size with the `?size` parameter, up to a maximum of 500.

include::{snippets}/page-example/curl-request.adoc[]
include::{snippets}/page-example/http-response.adoc[]

===== Response structure

include::{snippets}/page-example/response-fields.adoc[]

===== Links

include::{snippets}/page-example/links.adoc[]

=== Individual resources

==== Detailed representations

When fetching an individual resource, the response typically includes all attributes for that resource.
Nested resources are typically not included by default.

Example: When you fetch an individual sample, you get the detailed representation.

include::{snippets}/samples/fetch-one/curl-request.adoc[]
include::{snippets}/samples/fetch-one/http-response.adoc[]

==== Conditional requests

Most individual resources have entity tags and modification timestamps. This can be used to
make conditional requests, allowing clients to minimise bandwidth use and avoiding collisions with other
clients.

The format for conditional headers is specified in https://tools.ietf.org/html/rfc7232#section-3[RFC7232 section 3].
Note that only `If-Match`, `If-None-Match` and `If-Modified-Since` headers are supported.

===== Entity tags

Where entity tags are available, `ETag` values are included in the response headers. Updates to a resource
cause the ETag to change. You can make subsequent requests conditional on the resource currently matching or
not matching the last ETag value you hold.

For example, you can conditionally `GET` a resource if its `ETag` value has changed:
include::{snippets}/conditional-fetch-etag-get-if-none-match/curl-request.adoc[]
include::{snippets}/conditional-fetch-etag-get-if-none-match/http-response.adoc[]

You could `PUT`, `PATCH` or `DELETE` a resource if its `ETag` value has not changed:
include::{snippets}/conditional-delete-if-etag-match/curl-request.adoc[]
include::{snippets}/conditional-delete-if-etag-match/http-response.adoc[]


===== Last modified dates

Where modification timestamps are available, `Last-Modified` values are included in the response headers. You can make
subsequent requests conditional on the resource currently matching or not matching the last modified value you
hold.

You can conditionally `GET` a resource if it has changed since a specified time:
include::{snippets}/conditional-fetch-if-modified-since/curl-request.adoc[]
include::{snippets}/conditional-fetch-if-modified-since/http-response.adoc[]

The use of `ETag` is preferred over `Last-Modified`, as last modified dates are limited to a resolution of
one second.

== Resources

=== Root endpoint

You can issue a `GET` request to the root endpoint to get all the entry points into the API.

include::{snippets}/root-endpoint/curl-request.adoc[]
include::{snippets}/root-endpoint/http-response.adoc[]

=== Domains

=== Submissions

=== Submission contents

=== Domain contents

=== Status descriptions
















== Accessing submissions for a domain

=== Request structure

include::{snippets}/submissions/by-domain/http-request.adoc[]

=== Response fields

include::{snippets}/submissions/by-domain/response-fields.adoc[]
